version: '3'
services:
  my-app:
    image: 483931272607.dkr.ecr.us-east-2.amazonaws.com/my-app:1.6
    ports:
      - 80:80
  app-mongodb:
    container_name: app-mongodb
    image: mongo
    ports:
      - 27017:27017
    environment:
      - MONGO_INITDB_ROOT_USERNAME=admin
      - MONGO_INITDB_ROOT_PASSWORD=password
    volumes:
      - mongo-data:/data/db
  mongo-express:
    image: mongo-express
    ports:
      - 8080:8081
    environment:
      - ME_CONFIG_MONGODB_ADMINUSERNAME=admin
      - ME_CONFIG_MONGODB_ADMINPASSWORD=password
      - ME_CONFIG_MONGODB_SERVER=app-mongodb
volumes:
  mongo-data:
    driver: local
